FROM alpine:3.11

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk add tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata \
    && apk add dumb-init openvpn openvpn-auth-ldap openssl-dev \
    && rm -rf /var/cache/apk/*

ADD openvpn /etc/openvpn
ADD start.sh /

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/bin/sh","/start.sh"]
