name: OpenVPN

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '30 1 * * *'

env:
  BASEIMAGE: 'alpine:3.15'
  OPENVPN_VER: '2.5.6-r0'

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
        # ARM builds require QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
            #  - name: Extract metadata (tags, labels) for Docker
            #    id: meta
            #    uses: docker/metadata-action@v3
            #    with:
            #      images: |
            #        chaiyd/openvpn

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/s390x
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          build-args: |
            BASEIMAGE=${{ env.BASEIMAGE }}
            OPENVPN_VER=${{ env.OPENVPN_VER }}
          tags: |
            chaiyd/openvpn:${{ env.OPENVPN_VER }}
            chaiyd/openvpn
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: |
            chaiyd/openvpn:${{ env.OPENVPN_VER }}
          acs-report-enable: true
          fail-build: false

      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
